dist: xenial
language: python
python:
  - "3.7"
install:
  - sudo rm -f /etc/boto.cfg
  - pip install -r requirements.txt
script:
  - pytest --cov-report term --cov=app/test/
after_success:
  - codecov
