dist: xenial
sudo: true
env:
  - CODECOV_TOKEN=a85c4b22-159c-49a2-a813-e647c2045371
services:
  - docker
language: python
python:
  - "3.7"
before_install:
  - touch .env
  - docker-compose build tests
script:
  - make run_tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
