dist: xenial
sudo: true
env:
  - CODECOV_TOKEN="fc95eb88-890b-4473-b8cd-6d10d9c99c38"
services:
  - docker
language: python
python:
  - "3.7"
before_install:
  - touch .env
  - docker-compose build tests
script:
  - make run_tests
after_success:
  - bash <(curl -s https://codecov.io/bash)
