dist: xenial
sudo: true
services:
  - docker
language: python
python:
  - "3.7"
before_install:
  - touch src/.env
  - docker-compose build tests
script:
  - make run_tests
after_success:
  - codecov
