version: "3"
services:

  profiler:
    build:
      context: .
    container_name: "profiler-container"
    env_file: .env
    volumes:
      - ".:/code"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb-container"
    hostname: mongodb
    environment:
      MONGO_INITDB_DATABASE: profiler_db
    ports:
      - "27017:27017"
